<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618182249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, reason TEXT NOT NULL, github VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, techno_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE5C5087BC ON project (techno_id_id)');
        $this->addSql('CREATE TABLE project_feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89C97903166D1F9C ON project_feature (project_id)');
        $this->addSql('CREATE TABLE project_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6CA48E56166D1F9C ON project_status (project_id)');
        $this->addSql('CREATE TABLE project_techno (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE5C5087BC FOREIGN KEY (techno_id_id) REFERENCES project_techno (id)');
        $this->addSql('ALTER TABLE project_feature ADD CONSTRAINT FK_89C97903166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_status ADD CONSTRAINT FK_6CA48E56166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE5C5087BC');
        $this->addSql('ALTER TABLE project_feature DROP CONSTRAINT FK_89C97903166D1F9C');
        $this->addSql('ALTER TABLE project_status DROP CONSTRAINT FK_6CA48E56166D1F9C');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_feature');
        $this->addSql('DROP TABLE project_status');
        $this->addSql('DROP TABLE project_techno');
    }
}
