services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - pb_data:/pb/pb_data
      # optionnel si tu veux garder tes migrations/hooks en local
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks

volumes:
  pb_data:
