services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "4321"
    environment:
      API_URL: ${API_URL}
      MAILER_URL: ${MAILER_URL}

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8099:8080"
    volumes:
      - pb_data:/pb/pb_data
      # optionnel si tu veux garder tes migrations/hooks en local
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks

  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8085"
    environment:
      BREVO_API_KEY: ${BREVO_API_KEY}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
      PORT: ":8085"
    depends_on:
      - frontend

volumes:
  pb_data:
