<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: home.latte */
final class Template_e91a13e530 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h2>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 4:9 */;
		echo '</h2>
    <h3>Salut ma couille</h3>
';
	}
}
