<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: layout.latte */
final class Template_ab479ceb80 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html>
<head>
    <title>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 4:12 */;
		echo '</title>
</head>
<body>
<header>
    <h1>My Blog</h1>
    <nav>
        <a href="/">Home</a> |
        <a href="/login">Connexion</a>
        <a href="/register">Inscription</a>
        <a href="/logout">Déconnexion</a>
    </nav>
</header>
<main>
';
		$this->renderBlock('content', get_defined_vars()) /* pos 17:5 */;
		echo '</main>
<footer>
    <p>&copy; ';
		echo LR\HtmlHelpers::escapeText(date('Y')) /* pos 20:15 */;
		echo ' Flight Blog</p>
</footer>
</body>
</html>';
	}


	/** {block content} on line 17 */
	public function blockContent(array $ʟ_args): void
	{
	}
}
