<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: login.latte */
final class Template_a8e3939b67 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h2>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 4:9 */;
		echo '</h2>
    <nav>
        <a href="/">Home</a> |
        <a href="/register">Inscription</a>
    </nav>
    <form action="/login" method="post">

';
		if (isset($errors)) /* pos 11:9 */ {
			echo '            <h1>';
			echo LR\HtmlHelpers::escapeText($errors) /* pos 12:17 */;
			echo '</h1>
';
		}
		echo '
        <div class="">
            <label for="">Username</label>
            <input type="text" name="username">
        </div>

        <div class="">
            <label for="">Password</label>
            <input type="password" name="password">
        </div>

        <div class="">
            <button type="submit">Connexion</button>
        </div>
    </form>
';
	}
}
