<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: register.latte */
final class Template_fcfc8fbf3c extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 5:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h2>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 6:9 */;
		echo '</h2>
    <form action="/register" method="post">
        <div class="">
            <label for="">Username</label>
            <input type="text" name="username">
        </div>

        <div class="">
            <label for="">Password</label>
            <input type="password" name="password">
        </div>

        <div class="">
            <label for="">Confirm password</label>
            <input type="password" name="confirmPassword">
        </div>

        <div class="">
            <button type="submit">Inscription</button>
        </div>
    </form>
';
	}
}
